add profile information
shervik/ImageFeed-ios pull request #4
Opened 2023-03-06 20:29 UTC by shervik

2023-03-08 09:26 UTC, ABashkirova requested changes
Привет! Спринт выполнен верно, но есть грубая ошибка при работе с вью-контроллерами. Кажется мы ее фиксили в прошлой работе, но сейчас я вижу что не везде исправлено и у этого есть последствия:

При разлогине нельзя повторно авторизоваться из-за переиспользования вебвью, вероятно:
![RocketSim_Recording_iPhone_11_Pro_2023-03-08_11 08 00](https://user-images.githubusercontent.com/20269264/223674089-1a9175c4-a138-4692-9d0c-5e04580eac7e.gif)

В дебагере видно, что когда ты навигируешь к главному экрану, веб вью и авторизация все еще остаются жить во вью контроллере. Надо бы их удалять из иерархии, чтобы они в памяти не висели:
<img width="1501" alt="Снимок экрана 2023-03-08 в 11 19 10" src="https://user-images.githubusercontent.com/20269264/223674519-4e1a927a-d49a-454d-b882-61339b324983.png">



(Так же видно, что почему-то к аватарке не применяется скругление.  Это хорошо бы поправить тоже)

2023-03-08 09:26 UTC, ABashkirova commented on ImageFeed/Models/ProfileResult.swift
> +    }
Один из вариантов решения не писать инициализатор от транспортной модели, а писать метод-конвертор во вью модель у DTO.

Ну и часто этот метод нужен только в сервисе, поэтому создают отдельный приватный экстеншен к ProfileModel, и описывают его там (convertToViewModel)

2023-03-08 09:26 UTC, ABashkirova commented on ImageFeed/Presentation/AuthView/WebViewViewController.swift
> +                     self.updateProgress()
здесь можно справиться в одну строчку если не распаковывать self: self?.updateProgress

Обычно распаковывают скорее для удобства работы внутри комплишена, так как с опциональными значениями трудно работать. Здесь же такой необходимости нет

2023-03-08 09:26 UTC, ABashkirova commented on ImageFeed/Presentation/ProfileView/ProfilePresenter.swift
> +                OAuth2TokenStorage().removeObject(forKey: "token")
OAuth2TokenStorage() - это зависимость, и также по аналогии с вьюконтроллером и алертом долна передаваться через инициалитор.

2023-03-08 09:26 UTC, ABashkirova commented on ImageFeed/Presentation/ProfileView/ProfilePresenter.swift
> +            return
если showAvatar умеет работать с опционалами, тогда можно было сразу передать  URL(string: profileImageURL)

Но вопрос скорее в том, а почему showAvatar умеет принимать опционал? не очень понятно что он будет делать с nil, если ничего - может тогда и не вызывать его, или если что-то конкретное происходит, то может быть лучше тогда написать отдельный метод про это? чтобы явно показать твои намеренья

2023-03-08 09:26 UTC, ABashkirova commented on ImageFeed/Presentation/ProfileView/ProfileViewController.swift
> +    private var profileImageServiceObserver: NSObjectProtocol?
если уж ты пользуешься презентерами, то все сервисы стоит помещать именно внутрь презентера, вью контроллер в этом моменте должен стать только приемником пользовательских действий и экраном результата. Сейчас же получается что часть логики в презентере, а часть во вью контроллере, архитектурно не полностью реализована композиция

2023-03-08 09:26 UTC, ABashkirova commented on ImageFeed/Presentation/SplashView/SplashViewController.swift
> +                break
break был нужен чтобы пропускать блок кейса, когда в нем не было кода. Сейчас он здесь избыточен

2023-03-08 09:26 UTC, ABashkirova commented on ImageFeed/Presentation/SplashView/SplashViewController.swift
> +                UIBlockingProgressHUD.dismiss()
чтобы не повторяться можно поднять и вызвать перед switch

 UIBlockingProgressHUD.dismiss()

2023-03-08 09:26 UTC, ABashkirova commented on ImageFeed/Services/OAuth2/OAuth2Service.swift
> +                self.code = nil
Эту строчку нужно выполнить для обоих случаев.

2023-03-08 09:26 UTC, ABashkirova commented on ImageFeed/Services/OAuth2/OAuth2Service.swift
>                  }
А можно здесь возвращать body.accessToken? Мне кажется если токен пришел, то наверняка должен быть вызван комплишен, а здесь ты оставляешь шанс никогда его не вызвать

2023-03-08 09:26 UTC, ABashkirova commented on ImageFeed/Services/OAuth2/OAuth2TokenStorage.swift
> +    func removeObject(forKey: String) {
этот код можно вызывать в блоке else у  guard let token = newValue else { return }. 

Тогда опциональным значением получится затереть токен

2023-03-08 09:26 UTC, ABashkirova commented on ImageFeed/Presentation/SplashView/SplashViewController.swift
> +        tabBarViewController = TabBarController()
а зачем тебе хранить ссылку на vc? Ее будет хранить иерархия вью контроллеров на виндоу, разве нет нет?

2023-03-08 09:27 UTC, ABashkirova commented on ImageFeed/Presentation/SplashView/SplashViewController.swift
> +        tabBarViewController = TabBarController()
Нужно избавиться от этого подхода во всем приложении.

2023-03-11 06:44 UTC, ABashkirova approved these changes
круто!

2023-03-11 06:44 UTC, ABashkirova commented on ImageFeed/Services/OAuth2/OAuth2TokenStorage.swift
> +            keychain.set(token, forKey: "token")
👍🏻 

Теперь обе части у гварда равнозначны по исполняемому коду, назначение guard поменялось с защиты кода дальнейшего, на проверку условия для двух вевтлений, поэтому в таком случае принято переписывать на if-else

2023-03-11 06:56 UTC, shervik commented
> круто!

Большое спасибо за замечания! 💫

2023-03-11 08:17 UTC, merged