Sprint 12
shervik/ImageFeed-ios pull request #5
Opened 2023-03-15 20:06 UTC by shervik

2023-03-16 18:40 UTC, protos17 requested changes

2023-03-16 18:40 UTC, protos17 commented on ImageFeed/Services/OAuth2/OAuth2Service.swift
> +        if self.code != code { return }
if self.code == code { return } необходимо вернуть, иначе успешно нельзя авторизоваться

2023-03-16 18:40 UTC, protos17 commented on ImageFeed/Services/OAuth2/OAuth2Service.swift
> +//        task?.cancel()
Можно удалить совсем

2023-03-16 18:40 UTC, protos17 commented on ImageFeed/AppDelegate.swift
>          // Override point for customization after application launch.
Лишний закомментированный код рекомендую удалять

2023-03-16 18:40 UTC, protos17 commented on ImageFeed/Helpers/Date+Extensions.swift
> +        return dateFormatter.date(from: dateInString) ?? Date()
Здесь ты при отсутствии значения присваиваешь текущую дату, необходимо в таком случае лейбл оставлять пустым

2023-03-16 18:40 UTC, protos17 commented on ImageFeed/Presentation/ImagesListView/ImagesListViewController.swift
> +        presenter?.changeLike(photoId: photo.id, isLike: !photo.isLiked) { result in
Сильная ссылка, необходимо добавить weak self перед result

2023-03-16 18:40 UTC, protos17 commented on ImageFeed/Presentation/SingleImageViewController.swift
> +            secondCompletion: {
Сильная ссылка в замыкании, необходимо добавить weak self

2023-03-16 18:40 UTC, protos17 commented on ImageFeed/Presentation/SplashView/SplashViewController.swift
>              case .success(let body):
ЗДесь выше сильная ссылка

2023-03-16 18:40 UTC, protos17 commented on ImageFeed/Services/ImagesList/ImagesListService.swift
> +        task = networkService.data(for: photosRequest(page: nextPage)) { result in
Сильная ссылка, необходимо добавить weak self

2023-03-16 18:40 UTC, protos17 commented on ImageFeed/Services/ImagesList/ImagesListService.swift
> +        task = networkService.data(for: request) { result in
Сильная ссылка, стоит добавить weak self

2023-03-16 18:40 UTC, protos17 commented on ImageFeed/Services/OAuth2/OAuth2Service.swift
> +        task = networkService.data(for: authTokenRequest(code: code)) { result in
Сильная ссылка, необходимо добавить weak self

2023-03-16 18:40 UTC, protos17 commented on ImageFeed/Services/Profile/ProfileImageService.swift
> +        task = networkService.data(for: profileImageRequest(username: username)) { result in
Сильная ссылка, необходимо добавить weak self

2023-03-16 18:40 UTC, protos17 commented on ImageFeed/Services/Profile/ProfileService.swift
> +        task = networkService.data(for: profileRequest(token)) { result in
Сильная ссылка, стоит добавить weak self

2023-03-16 18:43 UTC, shervik commented on ImageFeed/Services/OAuth2/OAuth2Service.swift
> +        if self.code != code { return }
да, это было исправлено в последнем коммите около часа назад)

2023-03-17 12:00 UTC, protos17 approved these changes

2023-03-17 12:00 UTC, protos17 commented on ImageFeed/Presentation/AuthView/WebViewViewController.swift
> +//        progressView.progressTintColor = .ypBlack
Лишний закомментированный код рекомендую удалять

2023-03-17 14:12 UTC, merged